
DELIMITER //
CREATE PROCEDURE SELECT_STOCK_ADJUSTMENT(IN STOCK_ADJUSTMENT_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT STOCK_ADJUSTMENT_NUM,STOCK_ADJUSTMENT_DATE,STOCK_ADJUSTMENT_DESC, STOCK_ADJUSTMENT_NUM AS STOCK_ADJUSTMENT_NUM_OLD FROM stock_adjustment WHERE STOCK_ADJUSTMENT_NUM=STOCK_ADJUSTMENT_NUM_PARAM;
SELECT STOCK_ADJUSTMENTLINE_LINENUMBER,STOCK_NUM,STOCK_ADJUSTMENTLINE_STOCK_DESC,STOCK_ADJUSTMENTLINE_STOCK_QTY FROM stock_adjustmentline WHERE STOCK_ADJUSTMENT_NUM=STOCK_ADJUSTMENT_NUM_PARAM;

COMMIT;
END//