DELIMITER //
CREATE PROCEDURE UPDATE_STOCK_ADJUSTMENT (IN STOCK_ADJUSTMENT_NUM_PARAM VARCHAR(20), IN STOCK_ADJUSTMENT_DATE_PARAM DATE, IN STOCK_ADJUSTMENT_DESC_PARAM VARCHAR(255), STOCK_ADJUSTMENT_NUM_OLD_PARAM VARCHAR(20), IN STOCK_ADJUSTMENTLINE_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;
DELETE FROM stock_adjustmentline WHERE STOCK_ADJUSTMENT_NUM=STOCK_ADJUSTMENT_NUM_OLD_PARAM;
UPDATE stock_adjustment SET STOCK_ADJUSTMENT_NUM=STOCK_ADJUSTMENT_NUM_PARAM, STOCK_ADJUSTMENT_DATE=STOCK_ADJUSTMENT_DATE_PARAM, STOCK_ADJUSTMENT_DESC=STOCK_ADJUSTMENT_DESC_PARAM WHERE STOCK_ADJUSTMENT_NUM=STOCK_ADJUSTMENT_NUM_OLD_PARAM;

IF STOCK_ADJUSTMENTLINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT stock_adjustmentline VALUES ';

stockadjustmentline_loop:LOOP
IF REGEXP_INSTR(STOCK_ADJUSTMENTLINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',STOCK_ADJUSTMENT_NUM_PARAM,'",',SUBSTRING(STOCK_ADJUSTMENTLINE_PARAM,POS),')') INTO @STRNG;
LEAVE stockadjustmentline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(STOCK_ADJUSTMENTLINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',STOCK_ADJUSTMENT_NUM_PARAM,'",',SUBSTRING(STOCK_ADJUSTMENTLINE_PARAM,POS,LENGTH),'),') INTO @STRNG;
SELECT (REGEXP_INSTR(STOCK_ADJUSTMENTLINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP stockadjustmentline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;



COMMIT;
END//