DELIMITER //
CREATE PROCEDURE INSERT_DEBTOR (IN DEBTOR_NUM_PARAM VARCHAR(20),IN DEBTOR_NAME_PARAM VARCHAR(255), IN DEBTOR_ADDRESS_PARAM VARCHAR(255), IN DEBTOR_POSTCODE_PARAM VARCHAR(5), IN DEBTOR_PHONE_PARAM VARCHAR(15),IN DEBTOR_FAX_PARAM VARCHAR(15),IN DEBTOR_OTHER_DESC_PARAM VARCHAR(255),IN DEBTOR_CREDIT_TERM_PARAM ENUM('COD', '30', '45', '60', '90'),IN GL_ACC_NUM_PARAM INT,IN DEBTOR_NUM_OLD_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO debtor VALUES(DEBTOR_NUM_PARAM,DEBTOR_NAME_PARAM,DEBTOR_ADDRESS_PARAM,DEBTOR_POSTCODE_PARAM,DEBTOR_PHONE_PARAM,DEBTOR_FAX_PARAM,DEBTOR_OTHER_DESC_PARAM,DEBTOR_CREDIT_TERM_PARAM,DEFAULT);
COMMIT;
END










