
DELIMITER //
CREATE PROCEDURE SELECT_DEBTORLIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBTOR_NUM AS NUM, DEBTOR_NAME AS NAME,DEBTOR_ADDRESS AS ADDRESS, DEBTOR_POSTCODE AS POSTCODE,DEBTOR_PHONE AS PHONE,DEBTOR_FAX AS FAX,DEBTOR_OTHER_DESC AS 'OTHER DESCRIPTION',DEBTOR_CREDIT_TERM AS 'CREDIT_TERM' FROM debtor ORDER BY DEBTOR_NUM;
COMMIT;
END//