
DELIMITER //
CREATE PROCEDURE DELETE_DELIVERY_RETURN (IN DELIVERY_RETURN_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM delivery_return_stock WHERE DELIVERY_RETURN_NUM IN (';
SELECT CONCAT(@STRNG,DELIVERY_RETURN_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM delivery_returnline WHERE DELIVERY_RETURN_NUM IN (';
SELECT CONCAT(@STRNG,DELIVERY_RETURN_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM delivery_return WHERE DELIVERY_RETURN_NUM IN (';
SELECT CONCAT(@STRNG,DELIVERY_RETURN_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//