DELIMITER //
CREATE PROCEDURE INSERT_DELIVERY_RETURN (IN DEBTOR_NUM_PARAM VARCHAR(20), IN DEBTOR_NAME_PARAM VARCHAR(255),IN DEBTOR_ADDRESS_PARAM VARCHAR(255), IN DELIVERY_RETURN_NUM_PARAM VARCHAR(20), IN DELIVERY_RETURN_DATE_PARAM DATE, IN DELIVERY_RETURN_DESC_PARAM VARCHAR(255), IN DELIVERY_RETURN_NUM_OLD_PARAM VARCHAR(20), IN DELIVERY_RETURNLINE_PARAM VARCHAR(255), IN DELIVERY_RETURN_STOCK_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE POS1 INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;

INSERT delivery_return VALUES(DELIVERY_RETURN_NUM_PARAM,DELIVERY_RETURN_DATE_PARAM,DELIVERY_RETURN_DESC_PARAM,DEBTOR_NUM_PARAM);

IF DELIVERY_RETURNLINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT delivery_returnline VALUES ';

deliveryreturnline_loop:LOOP
IF REGEXP_INSTR(DELIVERY_RETURNLINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',DELIVERY_RETURN_NUM_PARAM,'",',SUBSTRING(DELIVERY_RETURNLINE_PARAM,POS),')') INTO @STRNG;
LEAVE deliveryreturnline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(DELIVERY_RETURNLINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',DELIVERY_RETURN_NUM_PARAM,'",',SUBSTRING(DELIVERY_RETURNLINE_PARAM,POS,LENGTH),'),') INTO @STRNG;
SELECT (REGEXP_INSTR(DELIVERY_RETURNLINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP deliveryreturnline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;

IF DELIVERY_RETURN_STOCK_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT delivery_return_stock VALUES ';

deliveryreturnstock_loop:LOOP
IF REGEXP_INSTR(DELIVERY_RETURN_STOCK_PARAM,'=',POS1)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',DELIVERY_RETURN_NUM_PARAM,'",',SUBSTRING(DELIVERY_RETURN_STOCK_PARAM,POS1),')') INTO @STRNG;
LEAVE deliveryreturnstock_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(DELIVERY_RETURN_STOCK_PARAM,'=',POS1) - POS1) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',DELIVERY_RETURN_NUM_PARAM,'",',SUBSTRING(DELIVERY_RETURN_STOCK_PARAM,POS1,LENGTH),'),') INTO @STRNG;
SELECT (REGEXP_INSTR(DELIVERY_RETURN_STOCK_PARAM,'=',POS1)+1) INTO POS1;
END;
END IF;
END LOOP deliveryreturnstock_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;

COMMIT;
END//