
DELIMITER //
CREATE PROCEDURE SELECT_DELIVERY_RETURNLIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DELIVERY_RETURN_NUM AS NUM, DEBTOR_NAME,DELIVERY_RETURN_DATE AS DATE,DELIVERY_RETURN_DESC AS DESCRIPTION,SUM(DELIVERY_RETURNLINE_STOCK_QTY) AS QTY FROM debtor JOIN delivery_return USING(DEBTOR_NUM) LEFT JOIN delivery_returnline USING (DELIVERY_RETURN_NUM) GROUP BY DELIVERY_RETURN_NUM ORDER BY DELIVERY_RETURN_NUM;
COMMIT;
END//