
DELIMITER //
CREATE PROCEDURE DELETE_DEBIT_NOTE (IN DEBIT_NOTE_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM debit_noteline WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
DELETE FROM debit_note_cash_receipt WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
DELETE FROM debit_note_bank_receipt WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
DELETE FROM debit_note_credit_note WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
DELETE FROM debit_note WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
COMMIT;
END//