
DELIMITER //
CREATE PROCEDURE DELETE_DEBIT_NOTE (IN DEBIT_NOTE_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM debit_noteline WHERE DEBIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,DEBIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note_cash_receipt WHERE DEBIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,DEBIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note_bank_receipt WHERE DEBIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,DEBIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note_credit_note WHERE DEBIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,DEBIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note WHERE DEBIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,DEBIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//