
DELIMITER //
CREATE PROCEDURE SELECT_DEBIT_NOTELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBIT_NOTE_NUM AS NUM,DEBTOR_NAME,DEBIT_NOTE_DATE AS DATE,DEBIT_NOTE_DESC AS DESCRIPTION, SUM(DEBIT_NOTELINE_SUBTOTAL) AS SUBTOTAL,
(SELECT SUM(DEBIT_NOTELINE_SUBTOTAL)
-IFNULL((SELECT SUM(DEBIT_NOTE_BANK_RECEIPT_AMOUNT) FROM debit_note_bank_receipt WHERE debit_note_bank_receipt.DEBIT_NOTE_NUM=debit_note.DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(DEBIT_NOTE_CASH_RECEIPT_AMOUNT) FROM debit_note_cash_receipt WHERE debit_note_cash_receipt.DEBIT_NOTE_NUM=debit_note.DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(DEBIT_NOTE_CREDIT_NOTE_AMOUNT) FROM debit_note_credit_note WHERE debit_note_credit_note.DEBIT_NOTE_NUM=debit_note.DEBIT_NOTE_NUM),0)) AS OUTSTANDING 
FROM debtor JOIN debit_note USING(DEBTOR_NUM) LEFT JOIN debit_noteline USING (DEBIT_NOTE_NUM) GROUP BY DEBIT_NOTE_NUM ORDER BY DEBIT_NOTE_NUM;
COMMIT;
END//