
DELIMITER //
CREATE PROCEDURE SELECT_DEBIT_NOTE_RECEIPT_HISTORY(IN DEBIT_NOTE_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT BANK_RECEIPT_NUM AS NUM, BANK_RECEIPT_DATE AS DATE,'BANK RECEIPT' AS TYPE, BANK_RECEIPT_TRANSACTION_ID AS DESCRIPTION, DEBIT_NOTE_BANK_RECEIPT_AMOUNT AS AMOUNT FROM bank_receipt NATURAL JOIN debit_note_bank_receipt WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM 
UNION ALL (SELECT CASH_RECEIPT_NUM, CASH_RECEIPT_DATE,'CASH RECEIPT', CASH_RECEIPT_TRANSACTION_ID, DEBIT_NOTE_CASH_RECEIPT_AMOUNT FROM cash_receipt NATURAL JOIN debit_note_cash_receipt WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM)
UNION ALL (SELECT CREDIT_NOTE_NUM, CREDIT_NOTE_DATE,'CREDIT NOTE', CREDIT_NOTE_DESC, DEBIT_NOTE_CREDIT_NOTE_AMOUNT FROM credit_note NATURAL JOIN debit_note_credit_note WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM);

COMMIT;
END//