
DELIMITER //
CREATE PROCEDURE SELECT_DEBIT_NOTE(IN DEBIT_NOTE_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBTOR_NUM, DEBTOR_NAME, DEBTOR_ADDRESS, DEBIT_NOTE_NUM,DEBIT_NOTE_DATE,DEBIT_NOTE_DESC,DEBIT_NOTE_CREDIT_TERM, debit_note.GL_ACC_NUM, DEBIT_NOTE_NUM AS DEBIT_NOTE_NUM_OLD FROM debtor JOIN debit_note USING (DEBTOR_NUM) WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
SELECT DEBIT_NOTELINE_LINENUMBER,DEBIT_NOTELINE_STOCK_NUM,DEBIT_NOTELINE_STOCK_DESC,DEBIT_NOTELINE_STOCK_PRICE,DEBIT_NOTELINE_STOCK_QTY,DEBIT_NOTELINE_DISCOUNT FROM debit_noteline WHERE DEBIT_NOTE_NUM=DEBIT_NOTE_NUM_PARAM;
COMMIT;
END//