
DELIMITER //
CREATE PROCEDURE SELECT_DEBIT_NOTELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBIT_NOTE_NUM,DEBTOR_NAME,DEBIT_NOTE_DATE,DEBIT_NOTE_DESC, SUM(DEBIT_NOTELINE_SUBTOTAL) AS DEBIT_NOTE_SUBTOTAL FROM debtor JOIN debit_note USING(DEBTOR_NUM) LEFT JOIN debit_noteline USING (DEBIT_NOTE_NUM) GROUP BY DEBIT_NOTE_NUM ORDER BY DEBIT_NOTE_NUM;
COMMIT;
END//