
DELIMITER //
CREATE PROCEDURE DELETE_DELIVERY_ORDER (IN DELIVERY_ORDER_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM delivery_orderline WHERE DELIVERY_ORDER_NUM IN (';
SELECT CONCAT(@STRNG,DELIVERY_ORDER_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM delivery_order WHERE DELIVERY_ORDER_NUM IN (';
SELECT CONCAT(@STRNG,DELIVERY_ORDER_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//