
DELIMITER //
CREATE PROCEDURE DELETE_DELIVERY_ORDER (IN DELIVERY_ORDER_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM delivery_orderline WHERE DELIVERY_ORDER_NUM=DELIVERY_ORDER_NUM_PARAM;
DELETE FROM delivery_order WHERE DELIVERY_ORDER_NUM=DELIVERY_ORDER_NUM_PARAM;
COMMIT;
END//