DELIMITER //
CREATE PROCEDURE INSERT_DELIVERY_ORDER (IN DEBTOR_NUM_PARAM VARCHAR(20), IN DEBTOR_NAME_PARAM VARCHAR(255),IN DEBTOR_ADDRESS_PARAM VARCHAR(255), IN DELIVERY_ORDER_NUM_PARAM VARCHAR(20), IN DELIVERY_ORDER_DATE_PARAM DATE, IN DELIVERY_ORDER_DESC_PARAM VARCHAR(255), IN DELIVERY_ORDER_NUM_OLD_PARAM VARCHAR(20), IN DELIVERY_ORDERLINE_PARAM VARCHAR(255),IN DELIVERY_ORDER_STOCK_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE POS1 INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;

INSERT delivery_order VALUES(DELIVERY_ORDER_NUM_PARAM,DELIVERY_ORDER_DATE_PARAM,DELIVERY_ORDER_DESC_PARAM,DEBTOR_NUM_PARAM);

IF DELIVERY_ORDERLINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT delivery_orderline VALUES ';

deliveryorderline_loop:LOOP
IF REGEXP_INSTR(DELIVERY_ORDERLINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',DELIVERY_ORDER_NUM_PARAM,'",',SUBSTRING(DELIVERY_ORDERLINE_PARAM,POS),')') INTO @STRNG;
LEAVE deliveryorderline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(DELIVERY_ORDERLINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',DELIVERY_ORDER_NUM_PARAM,'",',SUBSTRING(DELIVERY_ORDERLINE_PARAM,POS,LENGTH),'),') INTO @STRNG;
SELECT (REGEXP_INSTR(DELIVERY_ORDERLINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP deliveryorderline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;

IF DELIVERY_ORDER_STOCK_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT delivery_order_stock VALUES ';

deliveryorderstock_loop:LOOP
IF REGEXP_INSTR(DELIVERY_ORDER_STOCK_PARAM,'=',POS1)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',DELIVERY_ORDER_NUM_PARAM,'",',SUBSTRING(DELIVERY_ORDER_STOCK_PARAM,POS1),')') INTO @STRNG;
LEAVE deliveryorderstock_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(DELIVERY_ORDER_STOCK_PARAM,'=',POS1) - POS1) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',DELIVERY_ORDER_NUM_PARAM,'",',SUBSTRING(DELIVERY_ORDER_STOCK_PARAM,POS1,LENGTH),'),') INTO @STRNG;
SELECT (REGEXP_INSTR(DELIVERY_ORDER_STOCK_PARAM,'=',POS1)+1) INTO POS1;
END;
END IF;
END LOOP deliveryorderstock_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;



COMMIT;
END//