
DELIMITER //
CREATE PROCEDURE SELECT_DELIVERY_ORDER(IN DELIVERY_ORDER_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBTOR_NUM, DEBTOR_NAME, DEBTOR_ADDRESS, DELIVERY_ORDER_NUM,DELIVERY_ORDER_DATE,DELIVERY_ORDER_DESC, DELIVERY_ORDER_NUM AS DELIVERY_ORDER_NUM_OLD FROM debtor JOIN delivery_order USING (DEBTOR_NUM) WHERE DELIVERY_ORDER_NUM=DELIVERY_ORDER_NUM_PARAM;
SELECT DELIVERY_ORDERLINE_LINENUMBER,DELIVERY_ORDERLINE_STOCK_NUM,DELIVERY_ORDERLINE_STOCK_DESC,DELIVERY_ORDERLINE_STOCK_QTY FROM delivery_orderline WHERE DELIVERY_ORDER_NUM=DELIVERY_ORDER_NUM_PARAM;
SELECT DELIVERY_ORDERLINE_LINENUMBER,STOCK_NUM,DELIVERY_ORDER_STOCK_QTY FROM delivery_order_stock WHERE DELIVERY_ORDER_NUM=DELIVERY_ORDER_NUM_PARAM;
COMMIT;
END//