DELIMITER //
CREATE PROCEDURE UPDATE_ACCOUNT (IN GL_ACC_NUM_OLD_PARAM INT,IN GL_CATEGORY_PARAM VARCHAR(45), IN GL_ACC_NUM_PARAM INT, IN GL_DESC_PARAM VARCHAR(45))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
UPDATE gl SET GL_ACC_NUM=GL_ACC_NUM_PARAM, GL_DESC=GL_DESC_PARAM, GL_CATEGORY=GL_CATEGORY_PARAM,GL_STATUS='NORMAL' WHERE GL_ACC_NUM=GL_ACC_NUM_OLD_PARAM;
COMMIT;
END//
