
DELIMITER //
CREATE PROCEDURE DELETE_GOODS_RECEIVED_NOTE (IN GOODS_RECEIVED_NOTE_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM goods_received_noteline WHERE GOODS_RECEIVED_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,GOODS_RECEIVED_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM goods_received_note WHERE GOODS_RECEIVED_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,GOODS_RECEIVED_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//