DELIMITER //
CREATE PROCEDURE UPDATE_GOODS_RECEIVED_NOTE (IN CREDITOR_NUM_PARAM VARCHAR(20), IN CREDITOR_NAME_PARAM VARCHAR(255),IN CREDITOR_ADDRESS_PARAM VARCHAR(255), IN GOODS_RECEIVED_NOTE_NUM_PARAM VARCHAR(20), IN GOODS_RECEIVED_NOTE_DATE_PARAM DATE, IN GOODS_RECEIVED_NOTE_DESC_PARAM VARCHAR(255), GOODS_RECEIVED_NOTE_NUM_OLD_PARAM VARCHAR(20), IN GOODS_RECEIVED_NOTELINE_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;
DELETE FROM goods_received_noteline WHERE GOODS_RECEIVED_NOTE_NUM=GOODS_RECEIVED_NOTE_NUM_OLD_PARAM;
UPDATE goods_received_note SET GOODS_RECEIVED_NOTE_NUM=GOODS_RECEIVED_NOTE_NUM_PARAM, GOODS_RECEIVED_NOTE_DATE=GOODS_RECEIVED_NOTE_DATE_PARAM, GOODS_RECEIVED_NOTE_DESC=GOODS_RECEIVED_NOTE_DESC_PARAM, CREDITOR_NUM=CREDITOR_NUM_PARAM WHERE GOODS_RECEIVED_NOTE_NUM=GOODS_RECEIVED_NOTE_NUM_OLD_PARAM;

IF GOODS_RECEIVED_NOTELINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT goods_received_noteline VALUES ';

goodsreceivednoteline_loop:LOOP
IF REGEXP_INSTR(GOODS_RECEIVED_NOTELINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',GOODS_RECEIVED_NOTE_NUM_PARAM,'",',SUBSTRING(GOODS_RECEIVED_NOTELINE_PARAM,POS),')') INTO @STRNG;
LEAVE goodsreceivednoteline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(GOODS_RECEIVED_NOTELINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',GOODS_RECEIVED_NOTE_NUM_PARAM,'",',SUBSTRING(GOODS_RECEIVED_NOTELINE_PARAM,POS,LENGTH),'),') INTO @STRNG;
SELECT (REGEXP_INSTR(GOODS_RECEIVED_NOTELINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP goodsreceivednoteline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;



COMMIT;
END//