
DELIMITER //
CREATE PROCEDURE DELETE_PURCHASE_RETURN (IN PURCHASE_RETURN_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM purchase_return_stock WHERE PURCHASE_RETURN_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_RETURN_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_returnline WHERE PURCHASE_RETURN_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_RETURN_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_return WHERE PURCHASE_RETURN_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_RETURN_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//