
DELIMITER //
CREATE PROCEDURE DELETE_PURCHASE_RETURN (IN PURCHASE_RETURN_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM purchase_returnline WHERE PURCHASE_RETURN_NUM=PURCHASE_RETURN_NUM_PARAM;
DELETE FROM purchase_return WHERE PURCHASE_RETURN_NUM=PURCHASE_RETURN_NUM_PARAM;
COMMIT;
END//