
DELIMITER //
CREATE PROCEDURE SELECT_PURCHASE_RETURNLIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT PURCHASE_RETURN_NUM AS NUM, CREDITOR_NAME,PURCHASE_RETURN_DATE AS DATE,PURCHASE_RETURN_DESC AS DESCRIPTION,SUM(PURCHASE_RETURNLINE_STOCK_QTY) AS QTY FROM creditor JOIN purchase_return USING(CREDITOR_NUM) LEFT JOIN purchase_returnline USING (PURCHASE_RETURN_NUM) GROUP BY PURCHASE_RETURN_NUM ORDER BY PURCHASE_RETURN_NUM;
COMMIT;
END//