DELIMITER //
CREATE PROCEDURE INSERT_CREDITOR (IN CREDITOR_NUM_PARAM VARCHAR(10),IN CREDITOR_NAME_PARAM VARCHAR(255), IN CREDITOR_ADDRESS_PARAM VARCHAR(255), IN CREDITOR_POSTCODE_PARAM VARCHAR(5), IN CREDITOR_PHONE_PARAM VARCHAR(15),IN CREDITOR_FAX_PARAM VARCHAR(15),IN CREDITOR_OTHER_DESC_PARAM VARCHAR(255),IN CREDITOR_CREDIT_TERM_PARAM ENUM('COD', '30', '45', '60', '90'),IN GL_ACC_NUM INT,IN CREDITOR_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO creditor VALUES(CREDITOR_NUM_PARAM,CREDITOR_NAME_PARAM,CREDITOR_ADDRESS_PARAM,CREDITOR_POSTCODE_PARAM,CREDITOR_PHONE_PARAM,CREDITOR_FAX_PARAM,CREDITOR_OTHER_DESC_PARAM,CREDITOR_CREDIT_TERM_PARAM,DEFAULT);
COMMIT;
END










