
DELIMITER //
CREATE PROCEDURE SELECT_CREDITOR(IN CREDITOR_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,CREDITOR_NUM AS CREDITOR_NUM_OLD FROM creditor WHERE CREDITOR_NUM=CREDITOR_NUM_PARAM;
COMMIT;
END//