
DELIMITER //
CREATE PROCEDURE DELETE_BANK_PAYMENT (IN BANK_PAYMENT_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM purchase_invoice_bank_payment WHERE BANK_PAYMENT_NUM IN (';
SELECT CONCAT(@STRNG,BANK_PAYMENT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_debit_note_bank_payment WHERE BANK_PAYMENT_NUM IN (';
SELECT CONCAT(@STRNG,BANK_PAYMENT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM bank_payment WHERE BANK_PAYMENT_NUM IN (';
SELECT CONCAT(@STRNG,BANK_PAYMENT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//