DELIMITER //
CREATE PROCEDURE INSERT_BANK_PAYMENT (IN BANK_PAYMENT_NUM_PARAM VARCHAR(10),IN BANK_NUM_PARAM VARCHAR(10), IN CREDITOR_NUM_PARAM VARCHAR(10), IN BANK_PAYMENT_DATE_PARAM DATE, IN BANK_PAYMENT_METHOD_PARAM VARCHAR(45),IN BANK_PAYMENT_TRANSACTION_ID_PARAM VARCHAR(45),IN BANK_PAYMENT_DESC_PARAM VARCHAR(255),IN BANK_PAYMENT_AMOUNT_PARAM DECIMAL(10,2),IN GL_ACC_NUM_PARAM INT,IN BANK_PAYMENT_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO bank_payment VALUES(BANK_PAYMENT_NUM_PARAM,BANK_NUM_PARAM,CREDITOR_NUM_PARAM,BANK_PAYMENT_DATE_PARAM,BANK_PAYMENT_METHOD_PARAM,BANK_PAYMENT_TRANSACTION_ID_PARAM,BANK_PAYMENT_DESC_PARAM,BANK_PAYMENT_AMOUNT_PARAM,GL_ACC_NUM_PARAM);
COMMIT;
END










