
DELIMITER //
CREATE PROCEDURE SELECT_BANK_PAYMENTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT BANK_PAYMENT_NUM, BANK_PAYMENT_TRANSACTION_ID, BANK_PAYMENT_DATE, BANK_PAYMENT_METHOD, BANK_PAYMENT_DESC, BANK_PAYMENT_AMOUNT FROM bank_payment LEFT JOIN bank USING (BANK_NUM) ORDER BY BANK_PAYMENT_NUM;
COMMIT;
END//