
DELIMITER //
CREATE PROCEDURE SELECT_BANK_PAYMENTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT BANK_PAYMENT_NUM AS NUM, BANK_PAYMENT_TRANSACTION_ID AS 'TRANSACTION ID', BANK_PAYMENT_DATE AS DATE, BANK_PAYMENT_METHOD AS METHOD, BANK_PAYMENT_DESC AS DESCRIPTION, BANK_PAYMENT_AMOUNT AS AMOUNT FROM bank_payment LEFT JOIN bank USING (BANK_NUM) ORDER BY BANK_PAYMENT_NUM;
COMMIT;
END//