
DELIMITER //
CREATE PROCEDURE SELECT_BANK_PAYMENT(IN BANK_PAYMENT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,BANK_PAYMENT_NUM AS BANK_PAYMENT_NUM_OLD FROM bank_payment WHERE BANK_PAYMENT_NUM=BANK_PAYMENT_NUM_PARAM;
COMMIT;
END//