
DELIMITER //
CREATE PROCEDURE SELECT_PURCHASE_DEBIT_NOTELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT CREDITOR_NUM, CREDITOR_NAME, PURCHASE_DEBIT_NOTE_NUM,PURCHASE_DEBIT_NOTE_DATE,PURCHASE_DEBIT_NOTE_DESC, SUM(PURCHASE_DEBIT_NOTELINE_SUBTOTAL) AS PURCHASE_DEBIT_NOTE_SUBTOTAL FROM creditor JOIN purchase_debit_note USING(CREDITOR_NUM) LEFT JOIN purchase_debit_noteline USING (PURCHASE_DEBIT_NOTE_NUM) GROUP BY PURCHASE_DEBIT_NOTE_NUM ORDER BY PURCHASE_DEBIT_NOTE_NUM;
COMMIT;
END//