
DELIMITER //
CREATE PROCEDURE DELETE_CREDIT_NOTE (IN CREDIT_NOTE_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM credit_noteline WHERE CREDIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,CREDIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM sales_invoice_credit_note WHERE CREDIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,CREDIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note_credit_note WHERE CREDIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,CREDIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM credit_note WHERE CREDIT_NOTE_NUM IN (';
SELECT CONCAT(@STRNG,CREDIT_NOTE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//