
DELIMITER //
CREATE PROCEDURE SELECT_CREDIT_NOTELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT CREDIT_NOTE_NUM AS NUM,DEBTOR_NAME,CREDIT_NOTE_DATE AS DATE,CREDIT_NOTE_DESC AS DESCRIPTION, SUM(CREDIT_NOTELINE_SUBTOTAL) AS SUBTOTAL FROM debtor JOIN credit_note USING(DEBTOR_NUM) LEFT JOIN credit_noteline USING (CREDIT_NOTE_NUM) GROUP BY CREDIT_NOTE_NUM ORDER BY CREDIT_NOTE_NUM;
COMMIT;
END//