DELIMITER //
CREATE PROCEDURE UPDATE_CREDIT_NOTE (IN DEBTOR_NUM_PARAM VARCHAR(10), IN DEBTOR_NAME_PARAM VARCHAR(255),IN DEBTOR_ADDRESS_PARAM VARCHAR(255), IN CREDIT_NOTE_NUM_PARAM VARCHAR(10), IN CREDIT_NOTE_DATE_PARAM DATE, IN CREDIT_NOTE_DESC_PARAM VARCHAR(255), IN GL_ACC_NUM_PARAM INT, CREDIT_NOTE_NUM_OLD_PARAM VARCHAR(10), IN CREDIT_NOTELINE_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;
DELETE FROM credit_noteline WHERE CREDIT_NOTE_NUM=CREDIT_NOTE_NUM_OLD_PARAM;
UPDATE credit_note SET CREDIT_NOTE_NUM=CREDIT_NOTE_NUM_PARAM, CREDIT_NOTE_DATE=CREDIT_NOTE_DATE_PARAM, CREDIT_NOTE_DESC=CREDIT_NOTE_DESC_PARAM, DEBTOR_NUM=DEBTOR_NUM_PARAM, GL_ACC_NUM=GL_ACC_NUM_PARAM WHERE CREDIT_NOTE_NUM=CREDIT_NOTE_NUM_OLD_PARAM;

IF CREDIT_NOTELINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT credit_noteline VALUES ';

creditnoteline_loop:LOOP
IF REGEXP_INSTR(CREDIT_NOTELINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',CREDIT_NOTE_NUM_PARAM,'",',SUBSTRING(CREDIT_NOTELINE_PARAM,POS),',DEFAULT)') INTO @STRNG;
LEAVE creditnoteline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(CREDIT_NOTELINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',CREDIT_NOTE_NUM_PARAM,'",',SUBSTRING(CREDIT_NOTELINE_PARAM,POS,LENGTH),',DEFAULT),') INTO @STRNG;
SELECT (REGEXP_INSTR(CREDIT_NOTELINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP creditnoteline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;



COMMIT;
END//