
DELIMITER //
CREATE PROCEDURE SELECT_SALES_INVOICE(IN SALES_INVOICE_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBTOR_NUM, DEBTOR_NAME, DEBTOR_ADDRESS, SALES_INVOICE_NUM,SALES_INVOICE_DATE,SALES_INVOICE_DESC, SALES_INVOICE_CREDIT_TERM,sales_invoice.GL_ACC_NUM, SALES_INVOICE_NUM AS SALES_INVOICE_NUM_OLD FROM debtor JOIN sales_invoice USING (DEBTOR_NUM) WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_PARAM;
SELECT SALES_INVOICELINE_LINENUMBER,SALES_INVOICELINE_STOCK_NUM,SALES_INVOICELINE_STOCK_DESC,SALES_INVOICELINE_STOCK_PRICE,SALES_INVOICELINE_STOCK_QTY,SALES_INVOICELINE_DISCOUNT FROM sales_invoiceline WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_PARAM;
COMMIT;
END//