
DELIMITER //
CREATE PROCEDURE SELECT_SALES_INVOICELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT DEBTOR_NUM, DEBTOR_NAME, SALES_INVOICE_NUM,SALES_INVOICE_DATE,SALES_INVOICE_DESC, SUM(SALES_INVOICELINE_SUBTOTAL) AS SALES_INVOICE_SUBTOTAL FROM debtor JOIN sales_invoice USING(DEBTOR_NUM) LEFT JOIN sales_invoiceline USING (SALES_INVOICE_NUM) GROUP BY SALES_INVOICE_NUM ORDER BY SALES_INVOICE_NUM;
COMMIT;
END//