
DELIMITER //
CREATE PROCEDURE SELECT_SALES_INVOICELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT SALES_INVOICE_NUM AS NUM,DEBTOR_NAME,SALES_INVOICE_DATE AS DATE,SALES_INVOICE_DESC AS DESCRIPTION, SUM(SALES_INVOICELINE_SUBTOTAL) AS SUBTOTAL, 
(SELECT SUM(SALES_INVOICELINE_SUBTOTAL)
-IFNULL((SELECT SUM(SALES_INVOICE_BANK_RECEIPT_AMOUNT) FROM sales_invoice_bank_receipt WHERE sales_invoice_bank_receipt.SALES_INVOICE_NUM=sales_invoice.SALES_INVOICE_NUM),0)
-IFNULL((SELECT SUM(SALES_INVOICE_CASH_RECEIPT_AMOUNT) FROM sales_invoice_cash_receipt WHERE sales_invoice_cash_receipt.SALES_INVOICE_NUM=sales_invoice.SALES_INVOICE_NUM),0)
-IFNULL((SELECT SUM(SALES_INVOICE_CREDIT_NOTE_AMOUNT) FROM sales_invoice_credit_note WHERE sales_invoice_credit_note.SALES_INVOICE_NUM=sales_invoice.SALES_INVOICE_NUM),0)) AS OUTSTANDING 
FROM debtor JOIN sales_invoice USING(DEBTOR_NUM) LEFT JOIN sales_invoiceline USING (SALES_INVOICE_NUM) GROUP BY SALES_INVOICE_NUM ORDER BY SALES_INVOICE_NUM;

COMMIT;
END//