
DELIMITER //
CREATE PROCEDURE SELECT_SALES_INVOICE_RECEIPT_HISTORY(IN SALES_INVOICE_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT BANK_RECEIPT_NUM AS NUM, BANK_RECEIPT_DATE AS DATE,'BANK RECEIPT' AS TYPE, BANK_RECEIPT_TRANSACTION_ID AS DESCRIPTION, SALES_INVOICE_BANK_RECEIPT_AMOUNT AS AMOUNT FROM bank_receipt NATURAL JOIN sales_invoice_bank_receipt WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_PARAM 
UNION ALL (SELECT CASH_RECEIPT_NUM, CASH_RECEIPT_DATE,'CASH RECEIPT', CASH_RECEIPT_TRANSACTION_ID, SALES_INVOICE_CASH_RECEIPT_AMOUNT FROM cash_receipt NATURAL JOIN sales_invoice_cash_receipt WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_PARAM)
UNION ALL (SELECT CREDIT_NOTE_NUM, CREDIT_NOTE_DATE,'CREDIT NOTE', CREDIT_NOTE_DESC, SALES_INVOICE_CREDIT_NOTE_AMOUNT FROM credit_note NATURAL JOIN sales_invoice_credit_note WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_PARAM);

COMMIT;
END//