DELIMITER //
CREATE PROCEDURE UPDATE_SALES_INVOICE (IN DEBTOR_NUM_PARAM VARCHAR(10), IN DEBTOR_NAME_PARAM VARCHAR(255),IN DEBTOR_ADDRESS_PARAM VARCHAR(255), IN SALES_INVOICE_NUM_PARAM VARCHAR(10), IN SALES_INVOICE_DATE_PARAM DATE, IN SALES_INVOICE_DESC_PARAM VARCHAR(255), IN GL_ACC_NUM_PARAM INT, SALES_INVOICE_NUM_OLD_PARAM VARCHAR(10), IN SALES_INVOICELINE_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;
DELETE FROM sales_invoiceline WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_OLD_PARAM;
DELETE FROM sales_invoice_cash_receipt WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_OLD_PARAM;
DELETE FROM sales_invoice_bank_receipt WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_OLD_PARAM;
DELETE FROM sales_invoice_credit_note WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_OLD_PARAM;
UPDATE sales_invoice SET SALES_INVOICE_NUM=SALES_INVOICE_NUM_PARAM, SALES_INVOICE_DATE=SALES_INVOICE_DATE_PARAM, SALES_INVOICE_DESC=SALES_INVOICE_DESC_PARAM, DEBTOR_NUM=DEBTOR_NUM_PARAM, GL_ACC_NUM=GL_ACC_NUM_PARAM WHERE SALES_INVOICE_NUM=SALES_INVOICE_NUM_OLD_PARAM;

IF SALES_INVOICELINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT sales_invoiceline VALUES ';

invoiceline_loop:LOOP
IF REGEXP_INSTR(SALES_INVOICELINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',SALES_INVOICE_NUM_PARAM,'",',SUBSTRING(SALES_INVOICELINE_PARAM,POS),',DEFAULT)') INTO @STRNG;
LEAVE invoiceline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(SALES_INVOICELINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',SALES_INVOICE_NUM_PARAM,'",',SUBSTRING(SALES_INVOICELINE_PARAM,POS,LENGTH),',DEFAULT),') INTO @STRNG;
SELECT (REGEXP_INSTR(SALES_INVOICELINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP invoiceline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;



COMMIT;
END//