
DELIMITER //
CREATE PROCEDURE DELETE_CASH_RECEIPT (IN CASH_RECEIPT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM sales_invoice_cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;
DELETE FROM debit_note_cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;
DELETE FROM cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;
COMMIT;
END//