
DELIMITER //
CREATE PROCEDURE DELETE_CASH_RECEIPT (IN CASH_RECEIPT_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM sales_invoice_cash_receipt WHERE CASH_RECEIPT_NUM IN (';
SELECT CONCAT(@STRNG,CASH_RECEIPT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note_cash_receipt WHERE CASH_RECEIPT_NUM IN (';
SELECT CONCAT(@STRNG,CASH_RECEIPT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM cash_receipt WHERE CASH_RECEIPT_NUM IN (';
SELECT CONCAT(@STRNG,CASH_RECEIPT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//