DELIMITER //
CREATE PROCEDURE INSERT_CASH_RECEIPT (IN CASH_RECEIPT_NUM_PARAM VARCHAR(10), IN DEBTOR_NUM_PARAM VARCHAR(10), IN CASH_RECEIPT_DATE_PARAM DATE, IN CASH_RECEIPT_METHOD_PARAM VARCHAR(45),IN CASH_RECEIPT_TRANSACTION_ID_PARAM VARCHAR(45),IN CASH_RECEIPT_DESC_PARAM VARCHAR(255),IN CASH_RECEIPT_AMOUNT_PARAM DECIMAL(10,2),IN GL_ACC_NUM1_PARAM INT,IN GL_ACC_NUM2_PARAM INT,IN CASH_RECEIPT_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO cash_receipt VALUES(CASH_RECEIPT_NUM_PARAM,DEBTOR_NUM_PARAM,CASH_RECEIPT_DATE_PARAM,CASH_RECEIPT_METHOD_PARAM,CASH_RECEIPT_TRANSACTION_ID_PARAM,CASH_RECEIPT_DESC_PARAM,CASH_RECEIPT_AMOUNT_PARAM,GL_ACC_NUM1_PARAM,DEFAULT);
COMMIT;
END










