
DELIMITER //
CREATE PROCEDURE SELECT_CASH_RECEIPTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT CASH_RECEIPT_NUM AS NUM, CASH_RECEIPT_TRANSACTION_ID AS 'TRANSACTION ID', CASH_RECEIPT_DATE AS DATE, CASH_RECEIPT_METHOD AS METHOD, CASH_RECEIPT_DESC AS DESCRIPTION, CASH_RECEIPT_AMOUNT AS AMOUNT FROM cash_receipt ORDER BY CASH_RECEIPT_NUM;
COMMIT;
END//