
DELIMITER //
CREATE PROCEDURE SELECT_CASH_RECEIPT(IN CASH_RECEIPT_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT *,CASH_RECEIPT_NUM AS CASH_RECEIPT_NUM_OLD FROM cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;

SELECT SALES_INVOICE_NUM,SALES_INVOICE_CASH_RECEIPT_AMOUNT FROM sales_invoice_cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;

SELECT DEBIT_NOTE_NUM,DEBIT_NOTE_CASH_RECEIPT_AMOUNT FROM debit_note_cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;

COMMIT;
END//