
DELIMITER //
CREATE PROCEDURE SELECT_CASH_RECEIPT(IN CASH_RECEIPT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,CASH_RECEIPT_NUM AS CASH_RECEIPT_NUM_OLD FROM cash_receipt WHERE CASH_RECEIPT_NUM=CASH_RECEIPT_NUM_PARAM;
COMMIT;
END//