
DELIMITER //
CREATE PROCEDURE SELECT_CASH_RECEIPTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT CASH_RECEIPT_NUM, CASH_RECEIPT_TRANSACTION_ID, CASH_RECEIPT_DATE, CASH_RECEIPT_METHOD, CASH_RECEIPT_DESC, CASH_RECEIPT_AMOUNT FROM cash_receipt ORDER BY CASH_RECEIPT_NUM;
COMMIT;
END//