
DELIMITER //
CREATE PROCEDURE DELETE_CASH_PAYMENT (IN CASH_PAYMENT_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM purchase_invoice_cash_payment WHERE CASH_PAYMENT_NUM IN (';
SELECT CONCAT(@STRNG,CASH_PAYMENT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_debit_note_cash_payment WHERE CASH_PAYMENT_NUM IN (';
SELECT CONCAT(@STRNG,CASH_PAYMENT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM cash_payment WHERE CASH_PAYMENT_NUM IN (';
SELECT CONCAT(@STRNG,CASH_PAYMENT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//