
DELIMITER //
CREATE PROCEDURE DELETE_CASH_PAYMENT (IN CASH_PAYMENT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM purchase_invoice_cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;
DELETE FROM purchase_debit_note_cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;
DELETE FROM cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;
COMMIT;
END//