DELIMITER //
CREATE PROCEDURE INSERT_CASH_PAYMENT (IN CASH_PAYMENT_NUM_PARAM VARCHAR(10), IN CREDITOR_NUM_PARAM VARCHAR(10), IN CASH_PAYMENT_DATE_PARAM DATE, IN CASH_PAYMENT_METHOD_PARAM VARCHAR(45),IN CASH_PAYMENT_TRANSACTION_ID_PARAM VARCHAR(45),IN CASH_PAYMENT_DESC_PARAM VARCHAR(255),IN CASH_PAYMENT_AMOUNT_PARAM DECIMAL(10,2),IN GL_ACC_NUM1_PARAM INT,IN GL_ACC_NUM2_PARAM INT,IN CASH_PAYMENT_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO cash_payment VALUES(CASH_PAYMENT_NUM_PARAM,CREDITOR_NUM_PARAM,CASH_PAYMENT_DATE_PARAM,CASH_PAYMENT_METHOD_PARAM,CASH_PAYMENT_TRANSACTION_ID_PARAM,CASH_PAYMENT_DESC_PARAM,CASH_PAYMENT_AMOUNT_PARAM,GL_ACC_NUM1_PARAM,DEFAULT);
COMMIT;
END










