
DELIMITER //
CREATE PROCEDURE SELECT_CASH_PAYMENTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT CASH_PAYMENT_NUM AS NUM, CASH_PAYMENT_TRANSACTION_ID AS 'TRANSACTION ID', CASH_PAYMENT_DATE AS DATE, CASH_PAYMENT_METHOD AS METHOD, CASH_PAYMENT_DESC AS DESCRIPTION, CASH_PAYMENT_AMOUNT AS AMOUNT FROM cash_payment ORDER BY CASH_PAYMENT_NUM;
COMMIT;
END//