
DELIMITER //
CREATE PROCEDURE SELECT_CASH_PAYMENT(IN CASH_PAYMENT_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,CASH_PAYMENT_NUM AS CASH_PAYMENT_NUM_OLD FROM cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;

SELECT PURCHASE_INVOICE_NUM,PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT FROM purchase_invoice_cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;

SELECT PURCHASE_DEBIT_NOTE_NUM,PURCHASE_DEBIT_NOTE_CASH_PAYMENT_AMOUNT FROM purchase_debit_note_cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;

COMMIT;
END//