
DELIMITER //
CREATE PROCEDURE SELECT_CASH_PAYMENT(IN CASH_PAYMENT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,CASH_PAYMENT_NUM AS CASH_PAYMENT_NUM_OLD FROM cash_payment WHERE CASH_PAYMENT_NUM=CASH_PAYMENT_NUM_PARAM;
COMMIT;
END//