
DELIMITER //
CREATE PROCEDURE SELECT_CASH_PAYMENTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT CASH_PAYMENT_NUM, CASH_PAYMENT_TRANSACTION_ID, CASH_PAYMENT_DATE, CASH_PAYMENT_METHOD, CASH_PAYMENT_DESC, CASH_PAYMENT_AMOUNT FROM cash_payment ORDER BY CASH_PAYMENT_NUM;
COMMIT;
END//