DELIMITER //
CREATE PROCEDURE SELECT_DEBTOR_AGING() 
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT DEBTOR_NUM AS 'DEBTOR_NUM',DEBTOR_NAME AS NAME,SALES_INVOICE_NUM AS NUM, SALES_INVOICE_DATE AS DATE,
'SALES INVOICE' AS ITEM,
ROUND((SELECT SUM(SALES_INVOICELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(SALES_INVOICE_CASH_RECEIPT_AMOUNT) FROM sales_invoice_cash_receipt WHERE SALES_INVOICE_NUM=t1.SALES_INVOICE_NUM),0)
-IFNULL((SELECT SUM(SALES_INVOICE_BANK_RECEIPT_AMOUNT) FROM sales_invoice_bank_receipt WHERE SALES_INVOICE_NUM=t1.SALES_INVOICE_NUM),0)
-IFNULL((SELECT SUM(SALES_INVOICE_CREDIT_NOTE_AMOUNT) FROM sales_invoice_credit_note WHERE SALES_INVOICE_NUM=t1.SALES_INVOICE_NUM),0)
),2)as AMOUNT,SALES_INVOICE_CREDIT_TERM AS 'CREDIT_TERM'
FROM debtor JOIN sales_invoice USING (DEBTOR_NUM) NATURAL JOIN sales_invoiceline as t1 WHERE 
(SELECT SUM(SALES_INVOICELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(SALES_INVOICE_CASH_RECEIPT_AMOUNT) FROM sales_invoice_cash_receipt WHERE SALES_INVOICE_NUM=t2.SALES_INVOICE_NUM),0)
-IFNULL((SELECT SUM(SALES_INVOICE_BANK_RECEIPT_AMOUNT) FROM sales_invoice_bank_receipt WHERE SALES_INVOICE_NUM=t2.SALES_INVOICE_NUM),0)
-IFNULL((SELECT SUM(SALES_INVOICE_CREDIT_NOTE_AMOUNT) FROM sales_invoice_credit_note WHERE SALES_INVOICE_NUM=t2.SALES_INVOICE_NUM),0)
FROM debtor JOIN sales_invoice USING (DEBTOR_NUM) NATURAL JOIN sales_invoiceline as t2 WHERE t2.SALES_INVOICE_NUM=t1.SALES_INVOICE_NUM)>0
GROUP BY SALES_INVOICE_NUM 
UNION ALL 
(SELECT DEBTOR_NUM,DEBTOR_NAME,DEBIT_NOTE_NUM, DEBIT_NOTE_DATE,
'DEBIT NOTE',
ROUND((SELECT SUM(DEBIT_NOTELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(DEBIT_NOTE_CASH_RECEIPT_AMOUNT) FROM debit_note_cash_receipt WHERE DEBIT_NOTE_NUM=t3.DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(DEBIT_NOTE_BANK_RECEIPT_AMOUNT) FROM debit_note_bank_receipt WHERE DEBIT_NOTE_NUM=t3.DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(DEBIT_NOTE_CREDIT_NOTE_AMOUNT) FROM debit_note_credit_note WHERE DEBIT_NOTE_NUM=t3.DEBIT_NOTE_NUM),0)
),2)as AMOUNT, DEBIT_NOTE_CREDIT_TERM AS 'CREDIT_TERM'
FROM debtor JOIN debit_note USING (DEBTOR_NUM) NATURAL JOIN debit_noteline as t3 WHERE 
(SELECT SUM(DEBIT_NOTELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(DEBIT_NOTE_CASH_RECEIPT_AMOUNT) FROM debit_note_cash_receipt WHERE DEBIT_NOTE_NUM=t4.DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(DEBIT_NOTE_BANK_RECEIPT_AMOUNT) FROM debit_note_bank_receipt WHERE DEBIT_NOTE_NUM=t4.DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(DEBIT_NOTE_CREDIT_NOTE_AMOUNT) FROM debit_note_credit_note WHERE DEBIT_NOTE_NUM=t4.DEBIT_NOTE_NUM),0)
FROM debtor JOIN debit_note USING (DEBTOR_NUM) NATURAL JOIN debit_noteline as t4 WHERE t4.DEBIT_NOTE_NUM=t3.DEBIT_NOTE_NUM)>0
GROUP BY DEBIT_NOTE_NUM)
UNION ALL
(SELECT DEBTOR_NUM,DEBTOR_NAME,CREDIT_NOTE_NUM, CREDIT_NOTE_DATE,'CREDIT NOTE',
ROUND((SELECT -SUM(CREDIT_NOTELINE_SUBTOTAL) 
+IFNULL((SELECT SUM(SALES_INVOICE_CREDIT_NOTE_AMOUNT) FROM sales_invoice_credit_note WHERE CREDIT_NOTE_NUM=t5.CREDIT_NOTE_NUM),0)
+IFNULL((SELECT SUM(DEBIT_NOTE_CREDIT_NOTE_AMOUNT) FROM debit_note_credit_note WHERE CREDIT_NOTE_NUM=t5.CREDIT_NOTE_NUM),0)
),2),NULL
FROM debtor JOIN credit_note USING (DEBTOR_NUM) NATURAL JOIN credit_noteline as t5 WHERE 
(SELECT -SUM(CREDIT_NOTELINE_SUBTOTAL) 
+IFNULL((SELECT SUM(SALES_INVOICE_CREDIT_NOTE_AMOUNT) FROM sales_invoice_credit_note WHERE CREDIT_NOTE_NUM=t6.CREDIT_NOTE_NUM),0)
+IFNULL((SELECT SUM(DEBIT_NOTE_CREDIT_NOTE_AMOUNT) FROM debit_note_credit_note WHERE CREDIT_NOTE_NUM=t6.CREDIT_NOTE_NUM),0)
FROM debtor JOIN credit_note USING (DEBTOR_NUM) NATURAL JOIN credit_noteline as t6 WHERE t6.CREDIT_NOTE_NUM=t5.CREDIT_NOTE_NUM)<0
GROUP BY CREDIT_NOTE_NUM)
UNION ALL
(SELECT DEBTOR_NUM,DEBTOR_NAME,BANK_RECEIPT_NUM, BANK_RECEIPT_DATE,'BANK RECEIPT',
ROUND((SELECT -BANK_RECEIPT_AMOUNT 
+IFNULL((SELECT SUM(SALES_INVOICE_BANK_RECEIPT_AMOUNT) FROM sales_invoice_bank_receipt WHERE BANK_RECEIPT_NUM=t7.BANK_RECEIPT_NUM),0)
+IFNULL((SELECT SUM(DEBIT_NOTE_BANK_RECEIPT_AMOUNT) FROM debit_note_bank_receipt WHERE BANK_RECEIPT_NUM=t7.BANK_RECEIPT_NUM),0)
),2),NULL
FROM (debtor JOIN bank_receipt as t7 USING (DEBTOR_NUM)) WHERE 
(SELECT - BANK_RECEIPT_AMOUNT 
+IFNULL((SELECT SUM(SALES_INVOICE_BANK_RECEIPT_AMOUNT) FROM sales_invoice_bank_receipt WHERE BANK_RECEIPT_NUM=t8.BANK_RECEIPT_NUM),0)
+IFNULL((SELECT SUM(DEBIT_NOTE_BANK_RECEIPT_AMOUNT) FROM debit_note_bank_receipt WHERE BANK_RECEIPT_NUM=t8.BANK_RECEIPT_NUM),0)
FROM debtor JOIN bank_receipt as t8 USING (DEBTOR_NUM) WHERE t8.BANK_RECEIPT_NUM=t7.BANK_RECEIPT_NUM)<0
GROUP BY BANK_RECEIPT_NUM)
UNION ALL
(SELECT DEBTOR_NUM,DEBTOR_NAME,CASH_RECEIPT_NUM, CASH_RECEIPT_DATE,'CASH RECEIPT',
ROUND((SELECT -CASH_RECEIPT_AMOUNT 
+IFNULL((SELECT SUM(SALES_INVOICE_CASH_RECEIPT_AMOUNT) FROM sales_invoice_cash_receipt WHERE CASH_RECEIPT_NUM=t9.CASH_RECEIPT_NUM),0)
+IFNULL((SELECT SUM(DEBIT_NOTE_CASH_RECEIPT_AMOUNT) FROM debit_note_cash_receipt WHERE CASH_RECEIPT_NUM=t9.CASH_RECEIPT_NUM),0)
),2),NULL
FROM (debtor JOIN cash_receipt as t9 USING (DEBTOR_NUM)) WHERE 
(SELECT - CASH_RECEIPT_AMOUNT 
+IFNULL((SELECT SUM(SALES_INVOICE_CASH_RECEIPT_AMOUNT) FROM sales_invoice_cash_receipt WHERE CASH_RECEIPT_NUM=t10.CASH_RECEIPT_NUM),0)
+IFNULL((SELECT SUM(DEBIT_NOTE_CASH_RECEIPT_AMOUNT) FROM debit_note_cash_receipt WHERE CASH_RECEIPT_NUM=t10.CASH_RECEIPT_NUM),0)
FROM debtor JOIN cash_receipt as t10 USING (DEBTOR_NUM) WHERE t10.CASH_RECEIPT_NUM=t9.CASH_RECEIPT_NUM)<0
GROUP BY CASH_RECEIPT_NUM)
ORDER BY DEBTOR_NUM,DATE;

COMMIT;
END//