
DELIMITER //
CREATE PROCEDURE DELETE_BANK_RECEIPT (IN BANK_RECEIPT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM sales_invoice_bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;
DELETE FROM debit_note_bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;
DELETE FROM bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;
COMMIT;
END//