
DELIMITER //
CREATE PROCEDURE DELETE_BANK_RECEIPT (IN BANK_RECEIPT_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM sales_invoice_bank_receipt WHERE BANK_RECEIPT_NUM IN (';
SELECT CONCAT(@STRNG,BANK_RECEIPT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM debit_note_bank_receipt WHERE BANK_RECEIPT_NUM IN (';
SELECT CONCAT(@STRNG,BANK_RECEIPT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM bank_receipt WHERE BANK_RECEIPT_NUM IN (';
SELECT CONCAT(@STRNG,BANK_RECEIPT_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//