DELIMITER //
CREATE PROCEDURE INSERT_BANK_RECEIPT (IN BANK_RECEIPT_NUM_PARAM VARCHAR(10),IN BANK_NUM_PARAM VARCHAR(10), IN DEBTOR_NUM_PARAM VARCHAR(10), IN BANK_RECEIPT_DATE_PARAM DATE, IN BANK_RECEIPT_METHOD_PARAM VARCHAR(45),IN BANK_RECEIPT_TRANSACTION_ID_PARAM VARCHAR(45),IN BANK_RECEIPT_DESC_PARAM VARCHAR(255),IN BANK_RECEIPT_AMOUNT_PARAM DECIMAL(10,2),IN GL_ACC_NUM_PARAM INT,IN BANK_RECEIPT_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO bank_receipt VALUES(BANK_RECEIPT_NUM_PARAM,BANK_NUM_PARAM,DEBTOR_NUM_PARAM,BANK_RECEIPT_DATE_PARAM,BANK_RECEIPT_METHOD_PARAM,BANK_RECEIPT_TRANSACTION_ID_PARAM,BANK_RECEIPT_DESC_PARAM,BANK_RECEIPT_AMOUNT_PARAM,GL_ACC_NUM_PARAM);
COMMIT;
END










