
DELIMITER //
CREATE PROCEDURE SELECT_BANK_RECEIPT(IN BANK_RECEIPT_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT *,BANK_RECEIPT_NUM AS BANK_RECEIPT_NUM_OLD FROM bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;

SELECT SALES_INVOICE_NUM,SALES_INVOICE_BANK_RECEIPT_AMOUNT FROM sales_invoice_bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;

SELECT DEBIT_NOTE_NUM,DEBIT_NOTE_BANK_RECEIPT_AMOUNT FROM debit_note_bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;

COMMIT;
END//