
DELIMITER //
CREATE PROCEDURE SELECT_BANK_RECEIPT(IN BANK_RECEIPT_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,BANK_RECEIPT_NUM AS BANK_RECEIPT_NUM_OLD FROM bank_receipt WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM;
COMMIT;
END//