
DELIMITER //
CREATE PROCEDURE SELECT_BANK_RECEIPTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT BANK_RECEIPT_NUM AS NUM, BANK_RECEIPT_TRANSACTION_ID AS 'TRANSACTION ID', BANK_RECEIPT_DATE AS DATE, BANK_RECEIPT_METHOD AS METHOD, BANK_RECEIPT_DESC AS DESCRIPTION, BANK_RECEIPT_AMOUNT AS AMOUNT FROM bank_receipt LEFT JOIN bank USING (BANK_NUM) ORDER BY BANK_RECEIPT_NUM;
COMMIT;
END//