
DELIMITER //
CREATE PROCEDURE SELECT_BANK_RECEIPTLIST()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT BANK_RECEIPT_NUM, BANK_RECEIPT_TRANSACTION_ID, BANK_RECEIPT_DATE, BANK_RECEIPT_METHOD, BANK_RECEIPT_DESC, BANK_RECEIPT_AMOUNT FROM bank_receipt LEFT JOIN bank USING (BANK_NUM) ORDER BY BANK_RECEIPT_NUM;
COMMIT;
END//