DELIMITER //
CREATE PROCEDURE UPDATE_BANK_RECEIPT (IN BANK_RECEIPT_NUM_PARAM VARCHAR(10),IN BANK_NUM_PARAM VARCHAR(10), IN DEBTOR_NUM_PARAM VARCHAR(10), IN BANK_RECEIPT_DATE_PARAM DATE, IN BANK_RECEIPT_METHOD_PARAM VARCHAR(45),IN BANK_RECEIPT_TRANSACTION_ID_PARAM VARCHAR(45),IN BANK_RECEIPT_DESC_PARAM VARCHAR(255),IN BANK_RECEIPT_AMOUNT_PARAM DECIMAL(10,2),IN GL_ACC_NUM_PARAM INT,IN BANK_RECEIPT_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
UPDATE bank_receipt SET BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_PARAM,BANK_NUM=BANK_NUM_PARAM,DEBTOR_NUM=DEBTOR_NUM_PARAM,BANK_RECEIPT_DATE=BANK_RECEIPT_DATE_PARAM,BANK_RECEIPT_METHOD=BANK_RECEIPT_METHOD_PARAM,BANK_RECEIPT_TRANSACTION_ID=BANK_RECEIPT_TRANSACTION_ID_PARAM,BANK_RECEIPT_DESC=BANK_RECEIPT_DESC_PARAM,BANK_RECEIPT_AMOUNT=BANK_RECEIPT_AMOUNT_PARAM,GL_ACC_NUM=GL_ACC_NUM_PARAM WHERE BANK_RECEIPT_NUM=BANK_RECEIPT_NUM_OLD_PARAM;
COMMIT;
END//
