
DELIMITER //
CREATE PROCEDURE DELETE_JOURNAL (IN JOURNAL_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG ='DELETE FROM journalline WHERE JOURNAL_NUM IN (';
SELECT CONCAT(@STRNG,JOURNAL_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM journal WHERE JOURNAL_NUM IN (';
SELECT CONCAT(@STRNG,JOURNAL_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//