
DELIMITER //
CREATE PROCEDURE DELETE_JOURNAL (IN JOURNAL_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM journalline WHERE JOURNAL_NUM=JOURNAL_NUM_PARAM;
DELETE FROM journal WHERE JOURNAL_NUM=JOURNAL_NUM_PARAM;
COMMIT;
END//