
DELIMITER //
CREATE PROCEDURE SELECT_JOURNALLIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT JOURNAL_NUM,JOURNAL_DATE,JOURNAL_DESC, SUM(JOURNALLINE_DEBIT) AS NET_TOTAL FROM journal LEFT JOIN journalline USING (JOURNAL_NUM) GROUP BY JOURNAL_NUM ORDER BY JOURNAL_NUM;
COMMIT;
END//