
DELIMITER //
CREATE PROCEDURE SELECT_JOURNALLIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT JOURNAL_NUM AS NUM,JOURNAL_DATE AS DATE,JOURNAL_DESC AS DESCRIPTION, SUM(JOURNALLINE_DEBIT) AS 'NET TOTAL' FROM journal LEFT JOIN journalline USING (JOURNAL_NUM) GROUP BY JOURNAL_NUM ORDER BY JOURNAL_NUM;
COMMIT;
END//