
DELIMITER //
CREATE PROCEDURE SELECT_JOURNAL(IN JOURNAL_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT JOURNAL_NUM, JOURNAL_DATE, JOURNAL_DESC, JOURNAL_NUM AS JOURNAL_NUM_OLD FROM journal WHERE JOURNAL_NUM=JOURNAL_NUM_PARAM;
SELECT JOURNALLINE_LINENUMBER,GL_ACC_NUM,JOURNALLINE_GL_DESC,JOURNALLINE_DESC,JOURNALLINE_DEBIT,JOURNALLINE_CREDIT FROM journalline WHERE JOURNAL_NUM=JOURNAL_NUM_PARAM;
COMMIT;
END//