
DELIMITER //
CREATE PROCEDURE SELECT_STOCK(IN STOCK_NUM_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,STOCK_NUM AS STOCK_NUM_OLD FROM stock WHERE STOCK_NUM=STOCK_NUM_PARAM;
COMMIT;
END//