DELIMITER //
CREATE PROCEDURE SELECT_CREDITOR_AGING(IN CREDITOR_NUM_PARAM VARCHAR(255),IN CURRDATE_PARAM VARCHAR(255)) 
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SET @STRNG='';

SELECT CONCAT("SELECT CREDITOR_NUM AS 'CREDITOR_NUM',CREDITOR_NAME AS NAME,PURCHASE_INVOICE_NUM AS NUM, PURCHASE_INVOICE_DATE AS DATE,
'PURCHASE INVOICE' AS ITEM,
ROUND((SELECT SUM(PURCHASE_INVOICELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT) FROM purchase_invoice_cash_payment WHERE PURCHASE_INVOICE_NUM=t1.PURCHASE_INVOICE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_BANK_PAYMENT_AMOUNT) FROM purchase_invoice_bank_payment WHERE PURCHASE_INVOICE_NUM=t1.PURCHASE_INVOICE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_invoice_purchase_credit_note WHERE PURCHASE_INVOICE_NUM=t1.PURCHASE_INVOICE_NUM),0)
),2)as AMOUNT,PURCHASE_INVOICE_CREDIT_TERM AS 'CREDIT_TERM'
FROM creditor JOIN purchase_invoice USING (CREDITOR_NUM) NATURAL JOIN purchase_invoiceline as t1 WHERE CREDITOR_NUM IN (",CREDITOR_NUM_PARAM,
") AND PURCHASE_INVOICE_DATE<=",CURRDATE_PARAM," AND
(SELECT SUM(PURCHASE_INVOICELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT) FROM purchase_invoice_cash_payment WHERE PURCHASE_INVOICE_NUM=t2.PURCHASE_INVOICE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_BANK_PAYMENT_AMOUNT) FROM purchase_invoice_bank_payment WHERE PURCHASE_INVOICE_NUM=t2.PURCHASE_INVOICE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_invoice_purchase_credit_note WHERE PURCHASE_INVOICE_NUM=t2.PURCHASE_INVOICE_NUM),0)
FROM creditor JOIN purchase_invoice USING (CREDITOR_NUM) NATURAL JOIN purchase_invoiceline as t2 WHERE t2.PURCHASE_INVOICE_NUM=t1.PURCHASE_INVOICE_NUM)>0
GROUP BY PURCHASE_INVOICE_NUM 
UNION ALL 
(SELECT CREDITOR_NUM,CREDITOR_NAME,PURCHASE_DEBIT_NOTE_NUM, PURCHASE_DEBIT_NOTE_DATE,
'PURCHASE DEBIT NOTE',
ROUND((SELECT SUM(PURCHASE_DEBIT_NOTELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_CASH_PAYMENT_AMOUNT) FROM purchase_debit_note_cash_payment WHERE PURCHASE_DEBIT_NOTE_NUM=t3.PURCHASE_DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_BANK_PAYMENT_AMOUNT) FROM purchase_debit_note_bank_payment WHERE PURCHASE_DEBIT_NOTE_NUM=t3.PURCHASE_DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_debit_note_purchase_credit_note WHERE PURCHASE_DEBIT_NOTE_NUM=t3.PURCHASE_DEBIT_NOTE_NUM),0)
),2)as AMOUNT, PURCHASE_DEBIT_NOTE_CREDIT_TERM AS 'CREDIT_TERM'
FROM creditor JOIN purchase_debit_note USING (CREDITOR_NUM) NATURAL JOIN purchase_debit_noteline as t3 WHERE CREDITOR_NUM IN (",CREDITOR_NUM_PARAM,
") AND PURCHASE_DEBIT_NOTE_DATE<=",CURRDATE_PARAM," AND
(SELECT SUM(PURCHASE_DEBIT_NOTELINE_SUBTOTAL) 
-IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_CASH_PAYMENT_AMOUNT) FROM purchase_debit_note_cash_payment WHERE PURCHASE_DEBIT_NOTE_NUM=t4.PURCHASE_DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_BANK_PAYMENT_AMOUNT) FROM purchase_debit_note_bank_payment WHERE PURCHASE_DEBIT_NOTE_NUM=t4.PURCHASE_DEBIT_NOTE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_debit_note_purchase_credit_note WHERE PURCHASE_DEBIT_NOTE_NUM=t4.PURCHASE_DEBIT_NOTE_NUM),0)
FROM creditor JOIN purchase_debit_note USING (CREDITOR_NUM) NATURAL JOIN purchase_debit_noteline as t4 WHERE t4.PURCHASE_DEBIT_NOTE_NUM=t3.PURCHASE_DEBIT_NOTE_NUM)>0
GROUP BY PURCHASE_DEBIT_NOTE_NUM)
UNION ALL
(SELECT CREDITOR_NUM,CREDITOR_NAME,PURCHASE_CREDIT_NOTE_NUM, PURCHASE_CREDIT_NOTE_DATE,'PURCHASE CREDIT NOTE',
ROUND((SELECT -SUM(PURCHASE_CREDIT_NOTELINE_SUBTOTAL) 
+IFNULL((SELECT SUM(PURCHASE_INVOICE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_invoice_purchase_credit_note WHERE PURCHASE_CREDIT_NOTE_NUM=t5.PURCHASE_CREDIT_NOTE_NUM),0)
+IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_debit_note_purchase_credit_note WHERE PURCHASE_CREDIT_NOTE_NUM=t5.PURCHASE_CREDIT_NOTE_NUM),0)
),2),PURCHASE_CREDIT_NOTE_CREDIT_TERM AS 'CREDIT_TERM'
FROM creditor JOIN purchase_credit_note USING (CREDITOR_NUM) NATURAL JOIN purchase_credit_noteline as t5 WHERE CREDITOR_NUM IN (",CREDITOR_NUM_PARAM,
") AND PURCHASE_CREDIT_NOTE_DATE<=",CURRDATE_PARAM," AND
(SELECT -SUM(PURCHASE_CREDIT_NOTELINE_SUBTOTAL) 
+IFNULL((SELECT SUM(PURCHASE_INVOICE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_invoice_purchase_credit_note WHERE PURCHASE_CREDIT_NOTE_NUM=t6.PURCHASE_CREDIT_NOTE_NUM),0)
+IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_debit_note_purchase_credit_note WHERE PURCHASE_CREDIT_NOTE_NUM=t6.PURCHASE_CREDIT_NOTE_NUM),0)
FROM creditor JOIN purchase_credit_note USING (CREDITOR_NUM) NATURAL JOIN purchase_credit_noteline as t6 WHERE t6.PURCHASE_CREDIT_NOTE_NUM=t5.PURCHASE_CREDIT_NOTE_NUM)<0
GROUP BY PURCHASE_CREDIT_NOTE_NUM)
UNION ALL
(SELECT CREDITOR_NUM,CREDITOR_NAME,BANK_PAYMENT_NUM, BANK_PAYMENT_DATE,'BANK PAYMENT',
ROUND((SELECT -BANK_PAYMENT_AMOUNT 
+IFNULL((SELECT SUM(PURCHASE_INVOICE_BANK_PAYMENT_AMOUNT) FROM purchase_invoice_bank_payment WHERE BANK_PAYMENT_NUM=t7.BANK_PAYMENT_NUM),0)
+IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_BANK_PAYMENT_AMOUNT) FROM purchase_debit_note_bank_payment WHERE BANK_PAYMENT_NUM=t7.BANK_PAYMENT_NUM),0)
),2),NULL
FROM (creditor JOIN bank_payment as t7 USING (CREDITOR_NUM)) WHERE CREDITOR_NUM IN (",CREDITOR_NUM_PARAM,
") AND BANK_PAYMENT_DATE<=",CURRDATE_PARAM," AND
(SELECT - BANK_PAYMENT_AMOUNT 
+IFNULL((SELECT SUM(PURCHASE_INVOICE_BANK_PAYMENT_AMOUNT) FROM purchase_invoice_bank_payment WHERE BANK_PAYMENT_NUM=t8.BANK_PAYMENT_NUM),0)
+IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_BANK_PAYMENT_AMOUNT) FROM purchase_debit_note_bank_payment WHERE BANK_PAYMENT_NUM=t8.BANK_PAYMENT_NUM),0)
FROM creditor JOIN bank_payment as t8 USING (CREDITOR_NUM) WHERE t8.BANK_PAYMENT_NUM=t7.BANK_PAYMENT_NUM)<0
GROUP BY BANK_PAYMENT_NUM)
UNION ALL
(SELECT CREDITOR_NUM,CREDITOR_NAME,CASH_PAYMENT_NUM, CASH_PAYMENT_DATE,'CASH PAYMENT',
ROUND((SELECT -CASH_PAYMENT_AMOUNT 
+IFNULL((SELECT SUM(PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT) FROM purchase_invoice_cash_payment WHERE CASH_PAYMENT_NUM=t9.CASH_PAYMENT_NUM),0)
+IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_CASH_PAYMENT_AMOUNT) FROM purchase_debit_note_cash_payment WHERE CASH_PAYMENT_NUM=t9.CASH_PAYMENT_NUM),0)
),2),NULL
FROM (creditor JOIN cash_payment as t9 USING (CREDITOR_NUM)) WHERE CREDITOR_NUM IN (",CREDITOR_NUM_PARAM,
") AND CASH_PAYMENT_DATE<=",CURRDATE_PARAM," AND
(SELECT - CASH_PAYMENT_AMOUNT 
+IFNULL((SELECT SUM(PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT) FROM purchase_invoice_cash_payment WHERE CASH_PAYMENT_NUM=t10.CASH_PAYMENT_NUM),0)
+IFNULL((SELECT SUM(PURCHASE_DEBIT_NOTE_CASH_PAYMENT_AMOUNT) FROM purchase_debit_note_cash_payment WHERE CASH_PAYMENT_NUM=t10.CASH_PAYMENT_NUM),0)
FROM creditor JOIN cash_payment as t10 USING (CREDITOR_NUM) WHERE t10.CASH_PAYMENT_NUM=t9.CASH_PAYMENT_NUM)<0
GROUP BY CASH_PAYMENT_NUM)
ORDER BY CREDITOR_NUM,DATE") INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//