
DELIMITER //
CREATE PROCEDURE DELETE_PURCHASE_INVOICE (IN PURCHASE_INVOICE_NUM_PARAM VARCHAR(255))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;


SET @STRNG ='DELETE FROM purchase_invoiceline WHERE PURCHASE_INVOICE_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_INVOICE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_invoice_cash_payment WHERE PURCHASE_INVOICE_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_INVOICE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_invoice_bank_payment WHERE PURCHASE_INVOICE_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_INVOICE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_invoice_purchase_credit_note WHERE PURCHASE_INVOICE_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_INVOICE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @STRNG ='DELETE FROM purchase_invoice WHERE PURCHASE_INVOICE_NUM IN (';
SELECT CONCAT(@STRNG,PURCHASE_INVOICE_NUM_PARAM,')') INTO @STRNG;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

COMMIT;
END//