
DELIMITER //
CREATE PROCEDURE DELETE_PURCHASE_INVOICE (IN PURCHASE_INVOICE_NUM_PARAM VARCHAR(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
DELETE FROM purchase_invoiceline WHERE PURCHASE_INVOICE_NUM=PURCHASE_INVOICE_NUM_PARAM;
DELETE FROM purchase_invoice WHERE PURCHASE_INVOICE_NUM=PURCHASE_INVOICE_NUM_PARAM;
COMMIT;
END//