DELIMITER //
CREATE PROCEDURE INSERT_PURCHASE_INVOICE (IN CREDITOR_NUM_PARAM VARCHAR(20), IN CREDITOR_NAME_PARAM VARCHAR(255),IN CREDITOR_ADDRESS_PARAM VARCHAR(255), IN PURCHASE_INVOICE_NUM_PARAM VARCHAR(50), IN PURCHASE_INVOICE_DATE_PARAM DATE, IN PURCHASE_INVOICE_DESC_PARAM VARCHAR(255),IN PURCHASE_INVOICE_CREDIT_TERM_PARAM ENUM('COD','30','45','60','90'), IN GL_ACC_NUM_PARAM INT, IN PURCHASE_INVOICE_NUM_OLD_PARAM VARCHAR(50), IN PURCHASE_INVOICELINE_PARAM VARCHAR(255))
BEGIN
DECLARE POS INT DEFAULT 1;
DECLARE LENGTH INT DEFAULT 0;
DECLARE DONE VARCHAR(20) DEFAULT 'NO';

DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;

START TRANSACTION;

INSERT purchase_invoice VALUES(PURCHASE_INVOICE_NUM_PARAM,PURCHASE_INVOICE_DATE_PARAM,PURCHASE_INVOICE_DESC_PARAM,PURCHASE_INVOICE_CREDIT_TERM_PARAM,CREDITOR_NUM_PARAM,GL_ACC_NUM_PARAM);

IF PURCHASE_INVOICELINE_PARAM IS NOT NULL THEN 
BEGIN
SET @STRNG ='INSERT purchase_invoiceline VALUES ';

invoiceline_loop:LOOP
IF REGEXP_INSTR(PURCHASE_INVOICELINE_PARAM,'=',POS)=0 THEN 
BEGIN
SELECT CONCAT(@STRNG,'("',PURCHASE_INVOICE_NUM_PARAM,'",',SUBSTRING(PURCHASE_INVOICELINE_PARAM,POS),',DEFAULT)') INTO @STRNG;
LEAVE invoiceline_loop;
END;
ELSE 
BEGIN 
SELECT (REGEXP_INSTR(PURCHASE_INVOICELINE_PARAM,'=',POS) - POS) INTO LENGTH;
SELECT CONCAT(@STRNG,'("',PURCHASE_INVOICE_NUM_PARAM,'",',SUBSTRING(PURCHASE_INVOICELINE_PARAM,POS,LENGTH),',DEFAULT),') INTO @STRNG;
SELECT (REGEXP_INSTR(PURCHASE_INVOICELINE_PARAM,'=',POS)+1) INTO POS;
END;
END IF;
END LOOP invoiceline_loop;

PREPARE stmt FROM @STRNG;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

END;
END IF;

COMMIT;
END//