
DELIMITER //
CREATE PROCEDURE SELECT_PURCHASE_INVOICE_PAYMENT_HISTORY(IN PURCHASE_INVOICE_NUM_PARAM VARCHAR(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;

SELECT BANK_PAYMENT_NUM AS NUM, BANK_PAYMENT_DATE AS DATE,'BANK PAYMENT' AS TYPE, BANK_PAYMENT_TRANSACTION_ID AS DESCRIPTION, PURCHASE_INVOICE_BANK_PAYMENT_AMOUNT AS AMOUNT FROM bank_payment NATURAL JOIN purchase_invoice_bank_payment WHERE PURCHASE_INVOICE_NUM=PURCHASE_INVOICE_NUM_PARAM 
UNION ALL (SELECT CASH_PAYMENT_NUM, CASH_PAYMENT_DATE,'CASH PAYMENT', CASH_PAYMENT_TRANSACTION_ID, PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT FROM cash_payment NATURAL JOIN purchase_invoice_cash_payment WHERE PURCHASE_INVOICE_NUM=PURCHASE_INVOICE_NUM_PARAM)
UNION ALL (SELECT PURCHASE_CREDIT_NOTE_NUM, PURCHASE_CREDIT_NOTE_DATE,'PURCHASE CREDIT NOTE', PURCHASE_CREDIT_NOTE_DESC, PURCHASE_INVOICE_PURCHASE_CREDIT_NOTE_AMOUNT FROM purchase_credit_note NATURAL JOIN purchase_invoice_purchase_credit_note WHERE PURCHASE_INVOICE_NUM=PURCHASE_INVOICE_NUM_PARAM);

COMMIT;
END//