
DELIMITER //
CREATE PROCEDURE SELECT_PURCHASE_INVOICELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT PURCHASE_INVOICE_DATE AS DATE,CREDITOR_NAME,PURCHASE_INVOICE_NUM AS NUM, PURCHASE_INVOICE_DESC AS DESCRIPTION, SUM(PURCHASE_INVOICELINE_SUBTOTAL) AS SUBTOTAL,
(SELECT SUM(PURCHASE_INVOICELINE_SUBTOTAL)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_BANK_PAYMENT_AMOUNT) FROM purchase_invoice_bank_payment WHERE purchase_invoice_bank_payment.PURCHASE_INVOICE_NUM=purchase_invoice.PURCHASE_INVOICE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_CASH_PAYMENT_AMOUNT) FROM purchase_invoice_cash_payment WHERE purchase_invoice_cash_payment.PURCHASE_INVOICE_NUM=purchase_invoice.PURCHASE_INVOICE_NUM),0)
-IFNULL((SELECT SUM(PURCHASE_INVOICE_PURCHASE_CREDIT_NOTE_AMOUNT) FROM purchase_invoice_purchase_credit_note WHERE purchase_invoice_purchase_credit_note.PURCHASE_INVOICE_NUM=purchase_invoice.PURCHASE_INVOICE_NUM),0)) AS OUTSTANDING 
FROM creditor JOIN purchase_invoice USING(CREDITOR_NUM) LEFT JOIN purchase_invoiceline USING(PURCHASE_INVOICE_NUM) GROUP BY PURCHASE_INVOICE_NUM ORDER BY PURCHASE_INVOICE_DATE;
COMMIT;
END//