
DELIMITER //
CREATE PROCEDURE SELECT_PURCHASE_INVOICELIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT PURCHASE_INVOICE_NUM,CREDITOR_NAME,PURCHASE_INVOICE_DATE,purchase_invoice.GL_ACC_NUM, PURCHASE_INVOICE_DESC, SUM(PURCHASE_INVOICELINE_SUBTOTAL) AS PURCHASE_INVOICE_SUBTOTAL FROM creditor JOIN purchase_invoice USING(CREDITOR_NUM) LEFT JOIN purchase_invoiceline USING(PURCHASE_INVOICE_NUM) GROUP BY PURCHASE_INVOICE_NUM ORDER BY PURCHASE_INVOICE_NUM;
COMMIT;
END//