DELIMITER //
CREATE PROCEDURE INSERT_BANK (IN BANK_NUM_PARAM VARCHAR(10),IN BANK_NAME_PARAM VARCHAR(255), IN BANK_ADDRESS_PARAM VARCHAR(255), IN BANK_POSTCODE_PARAM VARCHAR(5), IN GL_ACC_NUM INT, IN BANK_NUM_OLD_PARAM VARCHAR(10))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
INSERT INTO bank VALUES(BANK_NUM_PARAM,BANK_NAME_PARAM,BANK_ADDRESS_PARAM,BANK_POSTCODE_PARAM,DEFAULT);
COMMIT;
END










