
DELIMITER //
CREATE PROCEDURE SELECT_BANK(IN BANK_NUM_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT *,BANK_NUM AS BANK_NUM_OLD FROM bank WHERE BANK_NUM=BANK_NUM_PARAM;
COMMIT;
END//