
DELIMITER //
CREATE PROCEDURE SELECT_BANKLIST ()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
SELECT BANK_NUM AS NUM, BANK_NAME AS NAME,BANK_ADDRESS AS ADDRESS, BANK_POSTCODE AS POSTCODE FROM bank ORDER BY BANK_NUM;
COMMIT;
END//