DELIMITER //
CREATE PROCEDURE UPDATE_BANK (IN BANK_NUM_PARAM VARCHAR(20),IN BANK_NAME_PARAM VARCHAR(255), IN BANK_ADDRESS_PARAM VARCHAR(255), IN BANK_POSTCODE_PARAM VARCHAR(5),IN GL_ACC_NUM_PARAM INT,IN BANK_NUM_OLD_PARAM VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
ROLLBACK;
RESIGNAL;
END;
START TRANSACTION;
UPDATE bank SET BANK_NUM=BANK_NUM_PARAM,BANK_NAME=BANK_NAME_PARAM,BANK_ADDRESS=BANK_ADDRESS_PARAM,BANK_POSTCODE=BANK_POSTCODE_PARAM,GL_ACC_NUM=DEFAULT WHERE BANK_NUM=BANK_NUM_OLD_PARAM;
COMMIT;
END//
